// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://blrqidlvvbqffekjbfhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJscnFpZGx2dmJxZmZla2piZmhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTcwNjksImV4cCI6MjA3MDQzMzA2OX0.eN52sZ_tF9hLCKR4aXMKPbXd6iM0v2685s7baPRSff0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});