// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bobmufpidfiukwphihmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvYm11ZnBpZGZpdWt3cGhpaG1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzg3MjIsImV4cCI6MjA1NjkxNDcyMn0.rgnO1t5uj1mE8v83Xq8vWOHk6grDpmzHQOuTub5HxDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);